name: company_app
description: A gentle AI life companion Flutter MVP for internal testing.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
