name: company_app
description: A gentle AI life companion Flutter MVP for internal testing.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  city_pickers: ^1.3.0
  cupertino_icons: ^1.0.9
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/fortune/
